build:
	@echo "==> Building"
	@docker build -t ederavilaprado-golang-installing-go .
	@echo "==> Done"
.PHONY: build

run:
	@echo "==> Running..."
	@docker run -it ederavilaprado-golang-installing-go
.PHONY: run